version: '3'
services:

  geoserver-lightning-db:
    image: timescale/timescaledb-ha:pg14-ts2.13
    container_name: geoserver-lightning-db
    restart: unless-stopped
    environment:
        POSTGRES_DB: weather
        POSTGRES_USER: ${DB_USER:-meteo}
        POSTGRES_PASSWORD: ${DB_PASSWORD:-meteo}
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - timescale-weather-db-storage:/home/postgres/pgdata/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - traefik-network

volumes:
  timescale-weather-db-storage:

networks:
    traefik-network:
      external: true
